/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package COM.DINUSHA.GUI;

import COM.DINUSHA.MODEL.Mysql;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinus
 */
public class LeavingStudentSelect extends javax.swing.JDialog {

    public StudentPositionManage stuPositionmng;
    public Leaving_Certificate leavingCertificate;

    boolean stuPositionM = true;
    boolean leavingStu = false;

    public LeavingStudentSelect(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadStudent("", "", "", "");

    }

    private void loadStudent(String adno, String fname, String lname, String email) {
        try {

            ResultSet resultSet = Mysql.executeSearch("SELECT * FROM student s\n"
                    + "              INNER JOIN class c ON s.class_id=c.id\n"
                    + "                 INNER JOIN intake i ON c.intake_id=i.id\n"
                    + "              INNER JOIN grade g ON i.grade_id=g.id\n"
                    + "                 INNER JOIN student_status ON s.student_status_id = student_status.id \n"
                    + "                 INNER JOIN gender ge ON s.gender_id = ge.id\n"
                    + " WHERE s.student_status_id != '4' AND s.student_status_id != '5' AND s.joined_date AND (s.id LIKE '%" + adno + "%' OR s.fname LIKE '%" + fname + "%' OR s.lname LIKE '%" + lname + "%' "
                    + " OR s.email LIKE '%" + email + "%')");

            DefaultTableModel model = (DefaultTableModel) table2.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("id"));
                vector.add(resultSet.getString("fname") + " " + resultSet.getString("lname"));
//                vector.add(resultSet.getString("lname"));
                vector.add(resultSet.getString("email"));
                vector.add(resultSet.getString("date_of_birth"));
                vector.add(resultSet.getString("g.name"));
                vector.add(resultSet.getString("c.name"));
                vector.add(resultSet.getString("ge.name"));
                vector.add(resultSet.getString("guardian_mobile"));
                vector.add(resultSet.getString("student_status.name"));
                vector.add(resultSet.getString("joined_date"));
               

                model.addRow(vector);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundPanel1 = new COM.DINUSHA.COMPONENT.RoundPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new componet.Table12();
        jLabel12 = new javax.swing.JLabel();
        roundTextField2 = new COM.DINUSHA.COMPONENT.roundTextField();
        roundbutton1 = new COM.DINUSHA.COMPONENT.roundbutton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Admission No", "Full Name", "Email", "Date of Birth", "Grade", "Class", "Gender", "Guardian Mobile", "Status", "Joined Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table2);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Search Students:");

        roundTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundTextField2ActionPerformed(evt);
            }
        });
        roundTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                roundTextField2KeyReleased(evt);
            }
        });

        roundbutton1.setBackground(new java.awt.Color(0, 0, 204));
        roundbutton1.setForeground(new java.awt.Color(255, 255, 255));
        roundbutton1.setText("Search");
        roundbutton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        roundbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roundTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roundbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 487, Short.MAX_VALUE)))
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roundTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(roundbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked

        int row = table2.getSelectedRow();

        String adno = String.valueOf(table2.getValueAt(row, 0));
        String name = String.valueOf(table2.getValueAt(row, 1));
        String dob = String.valueOf(table2.getValueAt(row, 3));
        String gender = String.valueOf(table2.getValueAt(row, 6));
        String doa = String.valueOf(table2.getValueAt(row, 9));

        if (evt.getClickCount() == 2) {
            if (leavingStu == true) {
                leavingCertificate.getadmissionNO().setText(adno);
                leavingCertificate.getStudentNAme().setText(name);
                leavingCertificate.getdob().setText(dob);
                leavingCertificate.getgender().setText(gender);
                leavingCertificate.getadmissionDate().setText(doa);
                this.dispose();

            } else {
                System.out.println("Not Selected");
            }
        }


    }//GEN-LAST:event_table2MouseClicked

    private void roundTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundTextField2ActionPerformed

    private void roundbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundbutton1ActionPerformed
        String search = roundTextField2.getText();
        loadStudent(search, search, search, search);
    }//GEN-LAST:event_roundbutton1ActionPerformed

    private void roundTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roundTextField2KeyReleased
        loadStudent("", "", "", "");
    }//GEN-LAST:event_roundTextField2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacLightLaf.setup();
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LeavingStudentSelect dialog = new LeavingStudentSelect(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private COM.DINUSHA.COMPONENT.RoundPanel roundPanel1;
    private COM.DINUSHA.COMPONENT.roundTextField roundTextField2;
    private COM.DINUSHA.COMPONENT.roundbutton roundbutton1;
    private componet.Table12 table2;
    // End of variables declaration//GEN-END:variables
}
