/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package COM.DINUSHA.GUI;

import COM.DINUSHA.COMPONENT.TextField;
import COM.DINUSHA.MODEL.Mysql;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.mysql.cj.x.protobuf.MysqlxCrud;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
//import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import raven.toast.Notifications;

public class Leaving_Certificate extends javax.swing.JFrame {

    /**
     * Creates new form Leaving_Certificate
     *
     * @return
     */
    public TextField getadmissionNO() {
        return adnoetextField1;
    }

    public TextField getStudentNAme() {
        return stunametextField2;
    }

    public TextField getdob() {
        return dobtextField4;
    }

    public TextField getgender() {
        return gendertextField11;
    }

    public TextField getadmissionDate() {
        return dateofaddmissiontextField8;
    }

    public Leaving_Certificate() {
        initComponents();
        init();
    }

    String currentDate;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    
    private void init(){
        Date currentdate = new Date();
        currentDate = sdf.format(currentdate);
        jDateChooser1.setDate(currentdate);
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundPanel3 = new COM.DINUSHA.COMPONENT.RoundPanel();
        jLabel5 = new javax.swing.JLabel();
        adnoetextField1 = new COM.DINUSHA.COMPONENT.TextField();
        jLabel6 = new javax.swing.JLabel();
        stunametextField2 = new COM.DINUSHA.COMPONENT.TextField();
        jLabel7 = new javax.swing.JLabel();
        dobtextField4 = new COM.DINUSHA.COMPONENT.TextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buttonGradient2 = new COM.DINUSHA.COMPONENT.ButtonGradient();
        mediumStudiedtextField5 = new COM.DINUSHA.COMPONENT.TextField();
        jLabel11 = new javax.swing.JLabel();
        religiontextField7 = new COM.DINUSHA.COMPONENT.TextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dateofaddmissiontextField8 = new COM.DINUSHA.COMPONENT.TextField();
        jLabel15 = new javax.swing.JLabel();
        ResonforLeavingtextField10 = new COM.DINUSHA.COMPONENT.TextField();
        gendertextField11 = new COM.DINUSHA.COMPONENT.TextField();
        parentnametextField12 = new COM.DINUSHA.COMPONENT.TextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lastgradeattendedtextField13 = new COM.DINUSHA.COMPONENT.TextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        prometdeCharactertextField14 = new COM.DINUSHA.COMPONENT.TextField();
        jLabel20 = new javax.swing.JLabel();
        checkedbytextField15 = new COM.DINUSHA.COMPONENT.TextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        buttonGradient1 = new COM.DINUSHA.COMPONENT.ButtonGradient();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        roundPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("Addmision No:");

        adnoetextField1.setEditable(false);
        adnoetextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adnoetextField1.setShadowColor(new java.awt.Color(0, 51, 153));
        adnoetextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adnoetextField1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setText("Student Name:");

        stunametextField2.setEditable(false);
        stunametextField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stunametextField2.setShadowColor(new java.awt.Color(0, 51, 153));
        stunametextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stunametextField2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setText("Date of Birth:");

        dobtextField4.setEditable(false);
        dobtextField4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dobtextField4.setShadowColor(new java.awt.Color(0, 51, 153));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setText("Date of Leaving:");

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setText("Mediun Studied:");

        buttonGradient2.setBackground(new java.awt.Color(204, 204, 204));
        buttonGradient2.setText("PRINT CERTIFICATE");
        buttonGradient2.setColor1(new java.awt.Color(0, 0, 153));
        buttonGradient2.setColor2(new java.awt.Color(0, 0, 102));
        buttonGradient2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonGradient2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonGradient2MouseClicked(evt);
            }
        });
        buttonGradient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient2ActionPerformed(evt);
            }
        });

        mediumStudiedtextField5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mediumStudiedtextField5.setShadowColor(new java.awt.Color(0, 51, 153));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel11.setText("Religion:");

        religiontextField7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        religiontextField7.setShadowColor(new java.awt.Color(0, 51, 153));
        religiontextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                religiontextField7ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel12.setText("Gender:");

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel13.setText("Date of Admission:");

        dateofaddmissiontextField8.setEditable(false);
        dateofaddmissiontextField8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateofaddmissiontextField8.setShadowColor(new java.awt.Color(0, 51, 153));
        dateofaddmissiontextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateofaddmissiontextField8ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel15.setText("Reason for Leaving:");

        ResonforLeavingtextField10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ResonforLeavingtextField10.setShadowColor(new java.awt.Color(0, 51, 153));

        gendertextField11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gendertextField11.setShadowColor(new java.awt.Color(0, 51, 153));
        gendertextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendertextField11ActionPerformed(evt);
            }
        });

        parentnametextField12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        parentnametextField12.setShadowColor(new java.awt.Color(0, 51, 153));

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel16.setText("Parent Name:");

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel17.setText("Last Grade Attened:");

        lastgradeattendedtextField13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lastgradeattendedtextField13.setShadowColor(new java.awt.Color(0, 51, 153));
        lastgradeattendedtextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastgradeattendedtextField13ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel18.setText("Grade of which the Student id promoted");

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel19.setText("character and conduct:");

        prometdeCharactertextField14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        prometdeCharactertextField14.setShadowColor(new java.awt.Color(0, 51, 153));

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel20.setText("Checked by:");

        checkedbytextField15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkedbytextField15.setShadowColor(new java.awt.Color(0, 51, 153));
        checkedbytextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkedbytextField15ActionPerformed(evt);
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setEnabled(false);
        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout roundPanel3Layout = new javax.swing.GroupLayout(roundPanel3);
        roundPanel3.setLayout(roundPanel3Layout);
        roundPanel3Layout.setHorizontalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roundPanel3Layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(roundPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(stunametextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roundPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dobtextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(roundPanel3Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13))))
                            .addGap(20, 20, 20)
                            .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(gendertextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(roundPanel3Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel12)))
                            .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(roundPanel3Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel11)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(roundPanel3Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(religiontextField7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel20))
                            .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(parentnametextField12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ResonforLeavingtextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prometdeCharactertextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(roundPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)))
                                    .addGroup(roundPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel10))
                                    .addGroup(roundPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mediumStudiedtextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(checkedbytextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addComponent(dateofaddmissiontextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel17))
                            .addGroup(roundPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lastgradeattendedtextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(112, 112, 112)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roundPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(roundPanel3Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(adnoetextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(389, Short.MAX_VALUE)))
        );
        roundPanel3Layout.setVerticalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(stunametextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gendertextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobtextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(religiontextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(46, 46, 46)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateofaddmissiontextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17)
                        .addGap(1, 1, 1)
                        .addComponent(lastgradeattendedtextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(5, 5, 5)
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mediumStudiedtextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel15)
                .addGap(5, 5, 5)
                .addComponent(ResonforLeavingtextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel16)
                .addGap(5, 5, 5)
                .addComponent(parentnametextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(0, 0, 0)
                .addComponent(jLabel19)
                .addGap(5, 5, 5)
                .addComponent(prometdeCharactertextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(5, 5, 5)
                .addComponent(checkedbytextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roundPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5)
                    .addGap(5, 5, 5)
                    .addComponent(adnoetextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(568, Short.MAX_VALUE)))
        );

        buttonGradient1.setText("SELECT STUDENT");
        buttonGradient1.setColor1(new java.awt.Color(0, 51, 204));
        buttonGradient1.setColor2(new java.awt.Color(51, 0, 102));
        buttonGradient1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonGradient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Leaving Certificate");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 25, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(buttonGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adnoetextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adnoetextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adnoetextField1ActionPerformed

    private void stunametextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stunametextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stunametextField2ActionPerformed

    private void buttonGradient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient2ActionPerformed

       // Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        String id = adnoetextField1.getText();

        String religion1 = religiontextField7.getText();
        String medium1 = mediumStudiedtextField5.getText();
        Date date = jDateChooser1.getDate();
        String rfl1 = ResonforLeavingtextField10.getText();
        String pn1 = parentnametextField12.getText();
        String lga1 = lastgradeattendedtextField13.getText();
        String pc1 = prometdeCharactertextField14.getText();
        String cb1 = checkedbytextField15.getText();

        if (religion1.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.INFO,
                    Notifications.Location.TOP_RIGHT, "Please fill Religion!");
        } else if (lga1.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.INFO,
                    Notifications.Location.TOP_RIGHT, "Please fill Last Grade Attened!");
        } else if (medium1.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.INFO,
                    Notifications.Location.TOP_RIGHT, "Please fill Mediun Studied!");
//        } else if (date.isEmpty()) {
//            Notifications.getInstance().show(Notifications.Type.INFO,
//                    Notifications.Location.TOP_RIGHT, "Please fill Date of Leaving!");
//        } else if (rfl1.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.INFO,
                    Notifications.Location.TOP_RIGHT, "Please fill Reson for leaving!");
        } else if (pn1.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.INFO,
                    Notifications.Location.TOP_RIGHT, "Please fill Parent name!");
        } else if (pc1.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.INFO,
                    Notifications.Location.TOP_RIGHT, "Please fill Promote character and conduct!");
        } else if (cb1.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.INFO,
                    Notifications.Location.TOP_RIGHT, "Please fill checked by fileld!");
        } else {

            try {

//                ResultSet resultSet = Mysql.executeSearch("SELECT * FROM student WHERE `status_id` = '2' AND `id` = '" + id + "'");
//
//                if (resultSet.next()) {
//                    JOptionPane.showMessageDialog(this, "Student Already Suspended", "Warning", JOptionPane.WARNING_MESSAGE);
//
//                } else {
                //  buttonGradient2.getActionListeners();
                int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Do you want Leved This student?", "Warning", JOptionPane.YES_NO_OPTION);

                if (showConfirmDialog == JOptionPane.YES_OPTION) {

                    if (id.equals(id)) {
                        Mysql.executeIUD("UPDATE leaving_certificate SET `count` = `count` + '1' , `reason` = '" + rfl1 + "' , `last_grade` = '" + lga1 + "' WHERE student_id = '" + id + "'");
                    } else {
                        Mysql.executeIUD("INSERT INTO leaving_certificate (`student_id`, `reason`, `count`, `last_grade`)"
                                + "VALUES ('" + id + "', '" + rfl1 + "', 1, '" + lga1 + "') ");

                    }
                    Mysql.executeIUD("UPDATE student SET student_status_id ='2' WHERE id = '" + id + "';");
//                    
                    JOptionPane.showMessageDialog(this, "Thish Student is Leaved!", "inform", JOptionPane.INFORMATION_MESSAGE);

                    String stuname = stunametextField2.getText();
                    String dob = dobtextField4.getText();
                    String gender = gendertextField11.getText();
                    String religion = religiontextField7.getText();
                    String adno = adnoetextField1.getText();
                    String doa = dateofaddmissiontextField8.getText();
                    String medium = mediumStudiedtextField5.getText();
                   // String dol = dateOfLeavingtextField6.getText();
                //  Date date = jDateChooser1.getDate();
                    String rfl = ResonforLeavingtextField10.getText();
                    String pn = parentnametextField12.getText();
                    String lga = lastgradeattendedtextField13.getText();
                    String pc = prometdeCharactertextField14.getText();
                    String cb = checkedbytextField15.getText();

                    HashMap<String, Object> map = new HashMap<>();
                    map.put("Parameter1", stuname);
                    map.put("Parameter2", dob);
                    map.put("Parameter3", gender);
                    map.put("Parameter4", religion);
                    map.put("Parameter5", adno);
                    map.put("Parameter6", doa);
                    map.put("Parameter7", medium);
                    map.put("Parameter8", currentDate);
                    map.put("Parameter9", rfl);
                    map.put("Parameter10", pn);
                    map.put("Parameter11", lga);
                    map.put("Parameter12", pc);
                    map.put("Parameter13", cb);
                    try {

                        InputStream s = this.getClass().getResourceAsStream("/Repots/Leavinggggggg.jasper");

                        JREmptyDataSource datasource = new JREmptyDataSource();
                        JasperPrint jasperPrint = JasperFillManager.fillReport(s, map, datasource);
                        JasperViewer.viewReport(jasperPrint, false);

                        System.out.println("success");

                        //    loadleavingStudent("fname", "ASC", "");
                        this.dispose();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                }

                // }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_buttonGradient2ActionPerformed

    private void religiontextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_religiontextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_religiontextField7ActionPerformed

    private void dateofaddmissiontextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateofaddmissiontextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateofaddmissiontextField8ActionPerformed

    private void gendertextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendertextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gendertextField11ActionPerformed

    private void lastgradeattendedtextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastgradeattendedtextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastgradeattendedtextField13ActionPerformed

    private void checkedbytextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkedbytextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkedbytextField15ActionPerformed

    private void buttonGradient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient1ActionPerformed
        JFrame parent = new JFrame();
        LeavingStudentSelect stuslct = new LeavingStudentSelect(parent, true);
        stuslct.leavingCertificate = this;
        stuslct.leavingStu = true;
        stuslct.setVisible(true);

    }//GEN-LAST:event_buttonGradient1ActionPerformed

    private void buttonGradient2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGradient2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGradient2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leaving_Certificate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private COM.DINUSHA.COMPONENT.TextField ResonforLeavingtextField10;
    private COM.DINUSHA.COMPONENT.TextField adnoetextField1;
    private COM.DINUSHA.COMPONENT.ButtonGradient buttonGradient1;
    private COM.DINUSHA.COMPONENT.ButtonGradient buttonGradient2;
    private COM.DINUSHA.COMPONENT.TextField checkedbytextField15;
    private COM.DINUSHA.COMPONENT.TextField dateofaddmissiontextField8;
    private COM.DINUSHA.COMPONENT.TextField dobtextField4;
    private COM.DINUSHA.COMPONENT.TextField gendertextField11;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private COM.DINUSHA.COMPONENT.TextField lastgradeattendedtextField13;
    private COM.DINUSHA.COMPONENT.TextField mediumStudiedtextField5;
    private COM.DINUSHA.COMPONENT.TextField parentnametextField12;
    private COM.DINUSHA.COMPONENT.TextField prometdeCharactertextField14;
    private COM.DINUSHA.COMPONENT.TextField religiontextField7;
    private COM.DINUSHA.COMPONENT.RoundPanel roundPanel3;
    private COM.DINUSHA.COMPONENT.TextField stunametextField2;
    // End of variables declaration//GEN-END:variables
}
