/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package COM.DASUN.GUI;


import COM.KAVINDU.Model.Mysql;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Frame;
import java.io.InputStream;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import raven.toast.Notifications;

/**
 *
 * @author dinus
 */
public class Student extends javax.swing.JDialog {

    private String id;

    /**
     * Creates new form GuardianRegisraion
     */
    public Student(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);
        initComponents();

        this.id = id;
        loadStudentData();

    }

    private void loadStudentData() {
        try {
            ResultSet rs = Mysql.executeSearch("SELECT * FROM  student s"
                    + " INNER JOIN guardian gu ON s.guardian_mobile = gu.mobile"
                    + " INNER JOIN  class c ON s.class_id = c.id"
                    + " INNER JOIN  gender g ON s.gender_id = g.id"
                    + " INNER JOIN  intake i ON c.intake_id = i.id"
                    + " INNER JOIN  grade gr ON i.grade_id = gr.id "
                    + " INNER JOIN student_status st ON s.student_status_id = st.id WHERE s.id = '" + this.id + "'");

            if (rs.next()) {

                textField1.setText(rs.getString("id"));
                textField2.setText(rs.getString("fname") + " " + rs.getString("lname"));
                textField3.setText(rs.getString("date_of_birth"));
                textField4.setText(rs.getString("joined_date"));
                textField5.setText(rs.getString("c.name") + " - " + rs.getString("gr.name"));
                textField6.setText(rs.getString("intake_name"));
                textField7.setText(rs.getString("email"));
                textField8.setText(rs.getString("g.name"));
                textField9.setText(rs.getString("st.name"));
                textField10.setText(rs.getString("guardian_mobile"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel4 = new components.RoundPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textField1 = new components.TextField();
        textField2 = new components.TextField();
        textField3 = new components.TextField();
        textField4 = new components.TextField();
        textField5 = new components.TextField();
        textField6 = new components.TextField();
        textField7 = new components.TextField();
        textField8 = new components.TextField();
        roundbutton1 = new components.roundbutton();
        jLabel10 = new javax.swing.JLabel();
        textField9 = new components.TextField();
        jLabel11 = new javax.swing.JLabel();
        textField10 = new components.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        roundPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Admission");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Student Detail Report");

        jLabel3.setText("Student Name");

        jLabel4.setText("DOB");

        jLabel5.setText("Joined Date ");

        jLabel6.setText("Class");

        jLabel7.setText("Email");

        jLabel8.setText("Intake");

        jLabel9.setText("Gender");

        textField1.setEditable(false);
        textField1.setForeground(new java.awt.Color(51, 51, 51));
        textField1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField1.setEnabled(false);

        textField2.setEditable(false);
        textField2.setForeground(new java.awt.Color(51, 51, 51));
        textField2.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField2.setEnabled(false);

        textField3.setEditable(false);
        textField3.setForeground(new java.awt.Color(51, 51, 51));
        textField3.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField3.setEnabled(false);

        textField4.setEditable(false);
        textField4.setForeground(new java.awt.Color(51, 51, 51));
        textField4.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField4.setEnabled(false);

        textField5.setEditable(false);
        textField5.setForeground(new java.awt.Color(51, 51, 51));
        textField5.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField5.setEnabled(false);

        textField6.setEditable(false);
        textField6.setForeground(new java.awt.Color(51, 51, 51));
        textField6.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField6.setEnabled(false);

        textField7.setEditable(false);
        textField7.setForeground(new java.awt.Color(51, 51, 51));
        textField7.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField7.setEnabled(false);

        textField8.setEditable(false);
        textField8.setForeground(new java.awt.Color(51, 51, 51));
        textField8.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField8.setEnabled(false);

        roundbutton1.setBackground(new java.awt.Color(0, 102, 255));
        roundbutton1.setForeground(new java.awt.Color(255, 255, 255));
        roundbutton1.setText("Print");
        roundbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundbutton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Student Status");

        textField9.setEditable(false);
        textField9.setForeground(new java.awt.Color(51, 51, 51));
        textField9.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField9.setEnabled(false);

        jLabel11.setText("Guardian Mobile");

        textField10.setEditable(false);
        textField10.setForeground(new java.awt.Color(51, 51, 51));
        textField10.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textField10.setEnabled(false);

        javax.swing.GroupLayout roundPanel4Layout = new javax.swing.GroupLayout(roundPanel4);
        roundPanel4.setLayout(roundPanel4Layout);
        roundPanel4Layout.setHorizontalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60)
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanel4Layout.createSequentialGroup()
                        .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(roundPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField9, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField10, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel4Layout.createSequentialGroup()
                        .addComponent(roundbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        roundPanel4Layout.setVerticalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(22, 22, 22)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(22, 22, 22)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(22, 22, 22)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(22, 22, 22)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(22, 22, 22)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(roundbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void roundbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundbutton1ActionPerformed
        try {
            // Retrieve user input from text fields
            String admission = textField1.getText();
            String studentName = textField2.getText();
            String DOB = textField3.getText();
            String joinedDate = textField4.getText();
            String grade = textField5.getText();
            String intake = textField6.getText();
            String email = textField7.getText();
            String gender = textField8.getText();
            String studentStatus = textField9.getText();
            String guardianMobile = textField10.getText();

            // Map parameters to the report
            HashMap<String, Object> params = new HashMap<>();
            params.put("Parameter1", admission);
            params.put("Parameter2", studentName);
            params.put("Parameter3", DOB);
            params.put("Parameter4", joinedDate);
            params.put("Parameter5", grade);
            params.put("Parameter6", intake);
            params.put("Parameter7", email);
            params.put("Parameter8", gender);
            params.put("Parameter9", studentStatus);
            params.put("Parameter10", guardianMobile);

            // Load the compiled .jasper report from resources
            InputStream s = this.getClass().getResourceAsStream("/reports/StudentReport.jasper");

            // Provide a dummy data source with 1 row (required for rendering)
            JREmptyDataSource dataSource = new JREmptyDataSource(1);

            // Fill the report with parameters and data source
            JasperPrint jasperPrint = JasperFillManager.fillReport(s, params, dataSource);

            // View the report
            JasperViewer.viewReport(jasperPrint, false);

            // Close the current form/window
            this.dispose();

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_roundbutton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //    FlatMacLightLaf.setup();
    /* Create and display the dialog */
    //    java.awt.EventQueue.invokeLater(new Runnable() {
    //       public void run() {
    //           Address dialog = new Address(new javax.swing.JFrame(), true);
    //          dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    //             @Override
    //             public void windowClosing(java.awt.event.WindowEvent e) {
    //                System.exit(0);
    //            }
    //        });
    //        dialog.setVisible(true);
    //     }
    //  });
    //  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private components.RoundPanel roundPanel4;
    private components.roundbutton roundbutton1;
    private components.TextField textField1;
    private components.TextField textField10;
    private components.TextField textField2;
    private components.TextField textField3;
    private components.TextField textField4;
    private components.TextField textField5;
    private components.TextField textField6;
    private components.TextField textField7;
    private components.TextField textField8;
    private components.TextField textField9;
    // End of variables declaration//GEN-END:variables

}
