/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package COM.AVISHKA.GUI;

import static COM.AVISHKA.GUI.UpdateEmReg.id;
import COM.AVISHKA.MODEL.Mysql;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Frame;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author PCVIEW
 */
public class ViewUpdate extends javax.swing.JDialog {

    //  static Frame parent1;
    static String id;
    static String fname;
    static String lname;
    static String mobile;
    static String email;
    static String joinedDate;
    static String username;

    static String gender;
    static String type;
    static String status;
    static String no;
    static String line1;
    static String line2;

    /**
     * Creates new form ViewUpdate
     */
    public ViewUpdate(java.awt.Frame parent, boolean modal, String id, String fname, String lname,
            String mobile, String email, String joinedDate, String username,
            String gender, String type, String status,String no,String line1,String line2) {
        super(parent, modal);
        initComponents();
        // this.parent1 = parent;
        this.id = id;
        this.fname = fname;
        this.lname = lname;
        this.mobile = mobile;
        this.email = email;
        this.joinedDate = joinedDate;
        this.username = username;

        this.gender = gender;
        this.type = type;
        this.status = status;
        this.no = no;
        this.line1 = line1;
        this.line2 = line2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        roundPanel1 = new COM.AVISHKA.COMPONENT.RoundPanel();
        buttonGradient3 = new COM.AVISHKA.COMPONENT.ButtonGradient();
        buttonGradient4 = new COM.AVISHKA.COMPONENT.ButtonGradient();
        buttonGradient5 = new COM.AVISHKA.COMPONENT.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("What do you want ?");

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));

        buttonGradient3.setText("Update Infomation");
        buttonGradient3.setColor1(new java.awt.Color(0, 51, 153));
        buttonGradient3.setColor2(new java.awt.Color(5, 30, 80));
        buttonGradient3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonGradient3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient3ActionPerformed(evt);
            }
        });

        buttonGradient4.setText("Update Address");
        buttonGradient4.setColor1(new java.awt.Color(0, 51, 153));
        buttonGradient4.setColor2(new java.awt.Color(5, 30, 80));
        buttonGradient4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonGradient4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient4ActionPerformed(evt);
            }
        });

        buttonGradient5.setText("Send Verify Code");
        buttonGradient5.setColor1(new java.awt.Color(0, 51, 153));
        buttonGradient5.setColor2(new java.awt.Color(5, 30, 80));
        buttonGradient5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonGradient4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGradient3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGradient5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(buttonGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonGradient4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonGradient5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGradient3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient3ActionPerformed

        JFrame parent = new JFrame();
        UpdateEmReg ue = new UpdateEmReg(parent, true, id, fname, lname, mobile, email, joinedDate, username, gender, type, status);

        try {
            
              ResultSet rs;
       
            rs = Mysql.executeSearch("SELECT `password` FROM `employee` WHERE `id`='" + id + "'");
            if (rs.next()) {
                String ps = rs.getString("password");
                
               ue.jPasswordField1.setText(ps);
            }
       
            Date edate = ue.jDateChooser1.getDate();
            Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            //  UpdateEmReg uer = new UpdateEmReg(parent1, true,"","","","","","","","","","");
            ue.roundTextField1.setText(id);
            ue.roundTextField3.setText(fname);
            ue.roundTextField4.setText(lname);
            ue.roundTextField2.setText(email);
            ue.roundTextField5.setText(mobile);
            ue.jDateChooser1.setDate(sdf.parse(joinedDate));
            ue.roundTextField6.setText(username);
            ue.jComboBox1.setSelectedItem(type);
            ue.jComboBox2.setSelectedItem(gender);
            ue.jComboBox3.setSelectedItem(status);
            ue.jComboBox1.setEnabled(false);
            ue.jComboBox2.setEnabled(false);
            
            
            ue.setVisible(true);

            this.dispose();

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_buttonGradient3ActionPerformed

    private void buttonGradient4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient4ActionPerformed
        // TODO add your handling code here:
        JFrame parent = new JFrame();
        EmpAdress ea = new EmpAdress(parent, true, mobile,no,line1,line2);
        
        ea.jLabel9.setText(mobile);
        ea.roundTextField1.setText(no);
        ea.roundTextField2.setText(line1);
        ea.roundTextField3.setText(line2);

        ea.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_buttonGradient4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacLightLaf.setup();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewUpdate dialog = new ViewUpdate(new javax.swing.JFrame(), true, "", "", "", "", "", "", "", "", "", "","","","");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private COM.AVISHKA.COMPONENT.ButtonGradient buttonGradient3;
    private COM.AVISHKA.COMPONENT.ButtonGradient buttonGradient4;
    private COM.AVISHKA.COMPONENT.ButtonGradient buttonGradient5;
    private javax.swing.JLabel jLabel9;
    private COM.AVISHKA.COMPONENT.RoundPanel roundPanel1;
    // End of variables declaration//GEN-END:variables
}
